server:
  port: 8082
spring:
  rabbitmq:
    host: 192.168.17.134
    port: 5672
    username: guest
    password: guest
    application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.17.134:3306/spingcloud_sell?characterEncoding=utf8&useSSL=false
  jpa:
    show-sql: true
girl:
  name: kitte
  age: 24
env:
  test2
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
